import Head from "next/head";
import { Inter } from "@next/font/google";
import { fetchData } from "../hooks/fetchData";
import Page from "../components/Page";
import { StarwarsCharacter, SwapiResponse } from "../types/TypesStarwars";
import Link from "next/link";
import { NextPage } from "next";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  characters: StarwarsCharacter[];
}

const Home: NextPage<Props> = ({ characters }) => {
  return (
    <Page>
      <Head>
        <title>StarWars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {characters?.map((character) => (
            <Link key={character.name} href="/character?id={p.id}" as={`/character/${character.url.slice(-2)}`}>
              <div key={character.name} className="flex justify-between py-3 border m-4 rounded-md  p-5 cursor-pointe hover:bg-blue-50">
                <p>{character.name}</p>
                <div>→</div>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </Page>
  );
};

Home.getInitialProps = async () => {
  const data = await fetchData<SwapiResponse>("https://swapi.dev/api/people/");
  return { characters: data.results as StarwarsCharacter[] };
};

export default Home;
